### ISSUE TITLE
Widok wyszukiwania ofert - pole search

### ISSUE THREAD

**Issue by LukaszSzarecki** [rsww-travel-agency/rsww-travel-agency-frontend#3]
**[ CEL ]**
**Jako** użytkownik
**Chce** widzieć pole search do wyszukiwania ofert i móc wskazać:

- cel podróży (kraj)
- data wyjazdu
- data powrotu
- liczba osób (osobno dorośli, osobno dzieci do lat 3)

**Aby** móc wyszukać konkretne oferty

**Comment by MD-00** [comment]
Funkcjonalność zrealizowana w #2 - zamykam issue.
