### ISSUE TITLE
Widok pojedynczej oferty - wyszukana oferta

### ISSUE THREAD

**Issue by LukaszSzarecki** [rsww-travel-agency/rsww-travel-agency-frontend#5]
**[ CEL ]**
**Jako** użytkownik
**Chce** widzieć wybraną ofertę z dużym zdjęciem i 
zawierającą takie informacje:

- kraj
- miasto
- hotel
- cena
- data przyjazdu, data odjazdu
- szczegóły hotelu
- rodzaje pokojów

**Aby** móc zarezerwować ofertę = kliknąć "rezerwuj"

**Comment by MD-00** [comment]
#13
